{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
    {{- include "ecommerce.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - port: 8080
      targetPort: 8080
{{- end }}
